### ISSUE TITLE
TypeError: The compressed data passed is corrupted

### ISSUE THREAD

**Issue by MrZBou** [Snowflake107/discord-ytdl-core#8]
I get this error with every created dispatchers on latest version (4.0.0)

```
...node_modules/.registry.npmjs.org/prism-media/1.2.2/node_modules/prism-media/src/opus/Opus.js:64
     return this.encoder.decode(buffer, Opus.name === 'opusscript' ? null : this._options.frameSize);
                         ^

 TypeError: The compressed data passed is corrupted
     at Decoder._decode (...node_modules/.registry.npmjs.org/prism-media/1.2.2/node_modules/prism-media/src/opus/Opus.js:64:25)
     at Decoder._transform (...node_modules/.registry.npmjs.org/prism-media/1.2.2/node_modules/prism-media/src/opus/Opus.js:189:20)
     at Decoder.Transform._read (_stream_transform.js:189:10)
     at Decoder.Transform._write (_stream_transform.js:177:12)
     at doWrite (_stream_writable.js:417:12)
     at writeOrBuffer (_stream_writable.js:401:5)
     at Decoder.Writable.write (_stream_writable.js:301:11)
     at Socket.ondata (_stream_readable.js:696:22)
     at Socket.emit (events.js:196:13)
     at addChunk (_stream_readable.js:290:12)
```

On 2.0.1 version everything works fine

**Comment by twlite** [comment]
@MrZBou can you please show the code where you have `ytdl(...)` and `VoiceConnection.play(...)` functions?

**Comment by twlite** [comment]
If your code looks  like this:
```js
const stream = ytdl("VIDEO_URL", {
    ...
});

connection.play(ytdl, { type: "opus" })
```

You have to add `opusEncoded: true` to ytdl options (for v4)
Your code should look like this:
```js
const stream = ytdl("VIDEO_URL", {
    opusEncoded: true,
    ...
});

connection.play(ytdl, { type: "opus" })
```

**Comment by MrZBou** [comment]
Yes, after adding a 'opusEncoded: true' everything worked. Thanks)
